import { Router } from 'express';
import AuthController from '../controllers/auth.Controller';
import CaptchaController from '../controllers/captcha.Controller';
import ParentCategoriesController from '../controllers/parent_categories.Controller';
import categoryController from '../controllers/category.Controller';
import productController from '../controllers/produc.Controller';
import orderController from '../controllers/order.Controller';
import productIntro from '../controllers/productIntro.Controller';

const router = Router();
router.get('/generate', CaptchaController.generate);
router.post('/register', AuthController.register);
router.post('/login', AuthController.login);
router.get('/verify-token', AuthController.verifyToken);
router.get('/profile', AuthController.getProfile);
router.get('/products/search?name=:name', categoryController.searchByName);
router.put('/:userId/password', AuthController.changePassword);
router.put('/:userId/profile', AuthController.updateProfile);
router.get('/categroy', ParentCategoriesController.Getcategroy); 
router.get('/categroy/:name', ParentCategoriesController.GetProduct) ; 
router.get('/products/:name', ParentCategoriesController.GetProductById);
router.post('/order/creact', orderController.createOrder);
router.get('/:userId/orders', orderController.getOrdersByUserId);
router.get('/productIntro', productIntro.getAll);
export default router;